[build]
  base = "CE_Massage_Frontend"
  command = "npx ng build --configuration production"
  publish = "dist/CE_Massage_Frontend/browser"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200